---
name: Pre-commit
on:
  pull_request:
  push:
    branches:
    - main
  merge_group:
permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - uses: actions/setup-go@v6.5.0
      with:
        go-version-file: go.mod
    - uses: hashicorp/setup-terraform@v4
    - uses: pre-commit/action@v3.0.1
